export type ScreenerRegion = "Estados Unidos" | "Europa" | "Canadá" | "Australia/global";

export type ScreenerUniverseCompany = {
  ticker: string;
  region: ScreenerRegion;
  country: string;
};

/**
 * Universo estable de 100 grandes cotizadas con liquidez y filings XBRL en
 * SEC. Incluye emisores internacionales mediante su acción o ADR registrado;
 * el orden solo fija los lotes de carga, nunca la clasificación final.
 */
export const QUALITY_SCREENER_UNIVERSE: ScreenerUniverseCompany[] = [
  { ticker: "AAPL", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "MSFT", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "NVDA", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "AMZN", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "GOOGL", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "META", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "TSLA", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "BRK-B", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "AVGO", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "LLY", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "JPM", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "V", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "WMT", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "XOM", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "UNH", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "MA", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "COST", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "JNJ", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "HD", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "PG", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ORCL", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ABBV", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "BAC", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "KO", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "NFLX", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "CRM", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "CVX", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "AMD", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "MRK", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "PEP", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "TMO", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "WFC", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "CSCO", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ACN", region: "Estados Unidos", country: "Irlanda" },
  { ticker: "MCD", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "IBM", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ABT", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "GE", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "CAT", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "QCOM", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "INTU", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "DIS", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "VZ", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "TXN", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "AMGN", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "NEE", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "PM", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "NOW", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "RTX", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "GS", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "SPGI", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "BKNG", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ISRG", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "AMAT", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "UBER", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "PFE", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "LOW", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "HON", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "COP", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ELV", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "SYK", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "BLK", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "C", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "DE", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "LMT", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ADP", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "MDLZ", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "TJX", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "GILD", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "CB", region: "Estados Unidos", country: "Suiza" },
  { ticker: "SCHW", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "PLD", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ADI", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "MMC", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "BMY", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "PANW", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ETN", region: "Estados Unidos", country: "Irlanda" },
  { ticker: "MU", region: "Estados Unidos", country: "Estados Unidos" },
  { ticker: "ASML", region: "Europa", country: "Países Bajos" },
  { ticker: "NVO", region: "Europa", country: "Dinamarca" },
  { ticker: "SAP", region: "Europa", country: "Alemania" },
  { ticker: "AZN", region: "Europa", country: "Reino Unido" },
  { ticker: "NVS", region: "Europa", country: "Suiza" },
  { ticker: "SHEL", region: "Europa", country: "Reino Unido" },
  { ticker: "TTE", region: "Europa", country: "Francia" },
  { ticker: "SNY", region: "Europa", country: "Francia" },
  { ticker: "UL", region: "Europa", country: "Reino Unido" },
  { ticker: "BP", region: "Europa", country: "Reino Unido" },
  { ticker: "HSBC", region: "Europa", country: "Reino Unido" },
  { ticker: "UBS", region: "Europa", country: "Suiza" },
  { ticker: "ING", region: "Europa", country: "Países Bajos" },
  { ticker: "BCS", region: "Europa", country: "Reino Unido" },
  { ticker: "RIO", region: "Australia/global", country: "Reino Unido/Australia" },
  { ticker: "BHP", region: "Australia/global", country: "Australia" },
  { ticker: "SHOP", region: "Canadá", country: "Canadá" },
  { ticker: "CNQ", region: "Canadá", country: "Canadá" },
  { ticker: "CNI", region: "Canadá", country: "Canadá" },
  { ticker: "CP", region: "Canadá", country: "Canadá" },
  { ticker: "ENB", region: "Canadá", country: "Canadá" },
  { ticker: "RY", region: "Canadá", country: "Canadá" },
];
